hosts:
  - http://localhost:8091
bucketName: example_bucket
logging:
  level: info
dcp:
  group:
    name: example_group
    membership:
      rebalanceDelay: 3s
metadata:
  config:
    bucket: metadata
    scope: example_scope
    collection: example_collection
  type: couchbase

cassandra:
  hosts:
    - localhost:9042
  keyspace: example_keyspace
  tableName: example_table
  timeout: 10s
  batchSizeLimit: 1000
  batchByteSizeLimit: 10485760
  workerCount: 4
  batchTickerDuration: 5s
  consistency: QUORUM
  collectionTableMapping:
    - collection: example_collection
      tableName: example_table
      fieldMappings:
        id: "id"
        partition_key: "partitionId"
        data: "documentData"
        metadata: "meta"
        status: "status"

appPort: :9001